# Generated by Django 5.2.2 on 2025-06-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
