# Generated by Django 5.2.2 on 2025-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_meterreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
