# Generated by Django 5.2.2 on 2025-07-07 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_rentrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cold_water', 'Холодная вода'), ('hot_water', 'Горячая вода'), ('electricity', 'Электричество')], max_length=20)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('usage', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('user', 'category', 'year', 'month')},
            },
        ),
    ]
